# VDSR config for training
MODEL:
  PRETRAIN: True
  WEIGHTS: "/data/jiangmingchao/data/output_ckpt_with_logs/AtrousNetEluUpWide_unia_416x416_adamw_cosine_l1closs_ssim_120_0.6_crop_data_LRX2/ckpt/SR-AtrousNet_best_loss_6.3994362354278564.pth"
  BACKBONE:
    NAME: "AtrousNetEluUpWide"
  ACTIVATION: "elu"
LOSS:
  L1_Charbonnier: True
  EPS: 0.001
  EDGE_LOSS: False
  MS_SSIM: False
  SSIM: True
  ALPHA: 1
TRAIN:
  GRAD_ACCUMULATE: False
  STEP: False
  GRAD_ACCUMULATE_STEP: 2
  MIX: False
  FP16: False
  LARS: False
  SAMPLER: False
  BATCH_SIZE: 8
  BASE_LR: 0.00004
  MOMENTUM: 0.9
  COSINE: True
  MAX_EPOCHS: 4
  WARM_EPOCHS: 0
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
DATAAUG:
  HFLIP: True
  VFLIP: True
  ROTATE: True
  RGB: True
  RANDOM_CROP: True
  MIXUP: False
  CUTMIX: False
  CUTBLUR: False
VALIDATION:
  STEP: 0
  USE: 1
  BATCH_SIZE: 8
  NUM_WORKERS: 8
  INTERVAL: 1
  ITER: 1000
SEED: 100
DATA:
  TRAIN:
    LR_PATH: "/data/jiangmingchao/data/dataset/sr_images_pred_train.log"
    HR_PATH: "/data/jiangmingchao/data/dataset/super2021_crop/train_sharp.log"
  VALIDATION:
    LR_PATH: "/data/jiangmingchao/data/SR_NTIRE2021/data/val/test_jpeg_from_val.log"
    HR_PATH: "/data/jiangmingchao/data/SR_NTIRE2021/data/val/test_gt_from_val.log"
# RGB
INPUT:
  MEAN: [111.35, 110.87, 107.35]
  STD: [64.24, 63.09, 67.95]
  NORM: False
  RANGE: 255
PATCH:
  STEP: 0
  PATCH_SIZE: [416, 416]
  MAX_NUMS: 400
DATALOADER:
  NUM_WORKERS: 12
CHEKCPOINTS:
  CKPT_PATH: "/data/jiangmingchao/data/output_ckpt_with_logs/64w_2epoch_4e-5_pretrain/ckpt"
  LOGS_PATH: "/data/jiangmingchao/data/output_ckpt_with_logs/64w_2epoch_4e-5_pretrain/logs"
DEBUG:
  SHOW_SR_IMAGE: False
  MAX_NUMBERS: 4
  PADDING: 16