# VDSR config for training
MODEL:
  PRETRAIN: False
  WEIGHTS: "/data/remote/github_code/OneFace/models/weights/resnet50.pth"
  BACKBONE:
    NAME: "waveletSrcnn"
  ACTIVATION: "elu"
LOSS:
  L1_Charbonnier: True
  EPS: 0.001
  EDGE_LOSS: False
  MS_SSIM: False
  SSIM: True
  ALPHA: 1
TRAIN:
  GRAD_ACCUMULATE: False
  STEP: False
  GRAD_ACCUMULATE_STEP: 2
  MIX: False
  FP16: False
  LARS: False
  SAMPLER: False
  BATCH_SIZE: 64
  BASE_LR: 0.00045
  MOMENTUM: 0.9
  COSINE: True
  MAX_EPOCHS: 150
  WARM_EPOCHS: 0
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
DATAAUG:
  HFLIP: True
  VFLIP: True
  ROTATE: True
  RGB: True
  RANDOM_CROP: True
  MIXUP: False
  CUTMIX: False
  CUTBLUR: False
VALIDATION:
  STEP: 0
  USE: 1
  BATCH_SIZE: 8
  NUM_WORKERS: 8
  INTERVAL: 1
  ITER: 1000
SEED: 100
DATA:
  TRAIN:
    LR_PATH: "/data/jiangmingchao/data/dataset/sr_images_pred_train.log"
    HR_PATH: "/data/jiangmingchao/data/dataset/super2021_crop/train_sharp.log"
  VALIDATION:
    LR_PATH: "/data/jiangmingchao/data/dataset/sr_images_pred_300_val.log"
    HR_PATH: "/data/jiangmingchao/data/dataset/hr_images_300_val.log"
# RGB
INPUT:
  MEAN: [111.35, 110.87, 107.35]
  STD: [64.24, 63.09, 67.95]
  NORM: False
  RANGE: 255
PATCH:
  STEP: 0
  PATCH_SIZE: [416, 416]
  MAX_NUMS: 400
DATALOADER:
  NUM_WORKERS: 12
CHEKCPOINTS:
  CKPT_PATH: "/data/jiangmingchao/data/output_ckpt_with_logs/WaveSrcnn_120epoch_64w/ckpt"
  LOGS_PATH: "/data/jiangmingchao/data/output_ckpt_with_logs/WaveSrcnn_120epoch_64w/logs"
DEBUG:
  SHOW_SR_IMAGE: False
  MAX_NUMBERS: 4
  PADDING: 16